pipeline {
    agent any

    parameters {
        booleanParam(name: 'CLEAN_START', defaultValue: false, description: 'Check this to run terraform destroy before provisioning')
        string(name: 'META_URL', defaultValue: '', description: 'Meta JSON URL e.g. http://10.16.96.16/kickstart/general/autogenerated/el9/ks_rhel-9.6-update-20251101.meta')
        string(name: 'IMAGE_NAME', defaultValue: 'rhel9-golden', description: 'Output image name (no extension required)')
        string(name: 'VM_COUNT', defaultValue: '2', description: 'Number of VMs to provision')
        choice(name: 'TAGS', choices: ['', 'level1-server', 'level1-workstation', 'level1-server,level1-workstation'], description: 'CIS level tags to apply (leave blank to run all tasks)')

    }

    stages {
        stage('Validate Parameters') {
            steps {
                script {
                    if (!params.META_URL?.trim()) {
                        error('META_URL is required.')
                    }

                    if (params.VM_COUNT == '') {
                        error('VM_COUNT is required.')
                    }

                    env.IMAGE_FILENAME = "${params.IMAGE_NAME}.qcow2"
                }
            }
        }

        stage('Checkout Terraform') {
            steps {
                dir('terraform') {
                    git branch: 'jenkins-terraform-integration',
                        url: 'https://github.com/defnotyujine/Terraform-KVM.git'
                }
            }
        }

        stage('Checkout Packer Repo') {
            steps {
                dir('packer') {
                    git branch: 'devel',
                        url: 'https://github.com/defnotyujine/Packer-Golden-Image-KVM.git'
                }
            }
        }

        stage('Checkout Ansible Repo') {
            steps {
                dir('ansible') {
                    git branch: 'devel',
                        url: 'https://github.com/defnotyujine/Jenkins-CIS-Hardening-Pipeline.git'
                }
            }
        }

        stage('Terraform Cleanup') {
            when {
                expression { params.CLEAN_START }
            }
            steps {
                script {
                    sh """
                        cd terraform/
                        terraform init
                        terraform destroy -auto-approve
                    """
                }
            }
        }

        stage('Install Collections') {
            steps {
                sh 'ansible-galaxy collection install -r ansible/requirements.yml'
            }
        }

        stage('Install Roles') {
            steps {
                sh 'ansible-galaxy role install -r ansible/requirements.yml -p ansible/playbooks/roles/ --force'
            }
        }

        stage('Fetch Meta + Download Boot Files') {
            steps {
                script {
                    def meta = sh(
                        script: "curl -sf '${params.META_URL}'",
                        returnStdout: true
                    ).trim()

                    def parsed = readJSON text: meta

                    sh "curl -sf -o /tmp/vmlinuz '${parsed.kernelLocation}'"
                    sh "curl -sf -o /tmp/initrd.img '${parsed.initrdLocation}'"

                    env.KERNEL_URL = '/tmp/vmlinuz'
                    env.INITRD_URL = '/tmp/initrd.img'

                    def kp = (parsed.kernelParameters ?: '').trim()
                    if (!kp.contains('inst.kexec'))    { kp += ' inst.kexec' }
                    if (!kp.contains('inst.reboot=0')) { kp += ' inst.reboot=0' }
                    env.KERNEL_PARAMS = kp.trim()

                    echo "Kernel: ${env.KERNEL_URL}"
                    echo "Initrd: ${env.INITRD_URL}"
                    echo "Params: ${env.KERNEL_PARAMS}"
                }
            }
        }

        stage('Packer Build + Harden') {
            steps {
                withCredentials([
                    string(credentialsId: 'packer-ssh-password', variable: 'SSH_PASS'),
                    string(credentialsId: 'ansible-vault-pass', variable: 'VAULT_PASS')
                ]) {
                    sh '''
                        set -e
                        printf "%s" "$VAULT_PASS" > /tmp/vault_pass.txt
                        chmod 600 /tmp/vault_pass.txt

                        cd packer
                        packer init .

                        PKR_VAR_kernel_url="$KERNEL_URL" \
                        PKR_VAR_initrd_url="$INITRD_URL" \
                        PKR_VAR_kernel_params="$KERNEL_PARAMS" \
                        PKR_VAR_ssh_password="$SSH_PASS" \
                        PKR_VAR_image_name="${IMAGE_FILENAME}" \
                        PACKER_LOG=1 packer build -force rhel.pkr.hcl
                    '''
                }
            }
        }

        stage('Upload Image') {
            steps {
                sh '''
                    KVM_HOST="frqadmin@192.168.122.1"

                    ssh -o StrictHostKeyChecking=no "$KVM_HOST" \
                        "rm -f /mnt/kvm_storage1/${IMAGE_FILENAME}"

                    scp -o StrictHostKeyChecking=no \
                        /var/lib/jenkins/packer-output/${IMAGE_FILENAME} \
                        "${KVM_HOST}:/mnt/kvm_storage1/"

                    ssh -o StrictHostKeyChecking=no "$KVM_HOST" \
                        "virsh pool-refresh kvmDatastore_qcow2_1"
                '''
            }
        }

        stage('Terraform Apply') {
            steps {
                sh """
                    cd terraform/
                    terraform init
                    terraform apply -auto-approve \
                        -var="vm_count=${params.VM_COUNT}" \
                        -var="golden_image_name=${env.IMAGE_FILENAME}" \
                        -var="vm_name=${params.IMAGE_NAME}"
                """
            }
        }

        stage('Generate Inventory') {
            steps {
                script {
                    def ips = sh(
                        script: "cd terraform/ && terraform output -json default-vm_ips | python3 -c \"import sys,json; print(','.join(json.load(sys.stdin)))\"",
                        returnStdout: true
                    ).trim()

                    def ipList = ips.split(',')
                    def hosts = ""
                    for (int i = 0; i < ipList.size(); i++) {
                        hosts += "   rhel_host${i + 1}:\n      ansible_host: ${ipList[i].trim()}\n"
                    }
                    writeFile file: 'ansible/sysconfig/inventory.yml', text: "all:\n  hosts:\n${hosts}"
                }
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                withCredentials([
                    string(
                        credentialsId: 'ansible-vault-pass',
                        variable: 'VAULT_PASS'
                    )
                ]) {
                    script {
                        def extraArgs = "--vault-password-file /tmp/vault_pass.txt --ssh-extra-args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"
                        if (params.TAGS) {
                            extraArgs += " --tags \"${params.TAGS}\""
                        }
                        sh 'echo $VAULT_PASS > /tmp/vault_pass.txt'
                        withEnv(["ANSIBLE_HOST_KEY_CHECKING=False"]) {
                            ansiblePlaybook(
                                playbook: 'ansible/playbooks/main_playbook.yml',
                                inventory: 'ansible/sysconfig/inventory.yml',
                                extras: extraArgs
                            )
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            sh 'rm -f /tmp/vault_pass.txt'
            echo 'Pipeline finished!'
        }
    }
}