pipeline {
    agent any

    parameters {
        string(name: 'META_URL', defaultValue: '', description: 'Meta JSON URL e.g. http://10.16.96.16/kickstart/general/autogenerated/el9/ks_rhel-9.6-update-20251101.meta')
        string(name: 'IMAGE_NAME', defaultValue: 'rhel9-golden.qcow2', description: 'Output image name')
        choice(
            name: 'HARDENING_TAGS',
            choices: ['', 'level1-server', 'level1-workstation', 'level1-server,level1-workstation'],
            description: 'CIS level tags to apply (blank = run all tasks)'
        )
    }

    stages {
        stage('Validate Parameters') {
            steps {
                script {
                    if (!params.META_URL?.trim()) {
                        error('META_URL is required.')
                    }
                }
            }
        }

        stage('Checkout Packer Repo') {
            steps {
                dir('packer') {
                    git branch: 'devel',
                        url: 'https://github.com/defnotyujine/Packer-Golden-Image-KVM.git'
                }
            }
        }

        stage('Checkout Ansible Repo') {
            steps {
                dir('ansible') {
                    git branch: 'main',
                        url: 'https://github.com/defnotyujine/Jenkins-CIS-Hardening-Pipeline.git'
                }
            }
        }

        stage('Prepare Ansible Dependencies') {
            steps {
                sh '''
                    set -e
                    cd ansible
                    ansible-galaxy collection install -r requirements.yml
                    ansible-galaxy role install -r requirements.yml -p playbooks/roles/ --force
                '''
            }
        }

        stage('Fetch Meta + Download Boot Files') {
            steps {
                script {
                    def meta = sh(
                        script: "curl -sf '${params.META_URL}'",
                        returnStdout: true
                    ).trim()

                    def parsed = readJSON text: meta

                    sh "curl -sf -o /tmp/vmlinuz '${parsed.kernelLocation}'"
                    sh "curl -sf -o /tmp/initrd.img '${parsed.initrdLocation}'"

                    env.KERNEL_URL = '/tmp/vmlinuz'
                    env.INITRD_URL = '/tmp/initrd.img'

                    def kp = (parsed.kernelParameters ?: '').trim()
                    if (!kp.contains('inst.kexec'))    { kp += ' inst.kexec' }
                    if (!kp.contains('inst.reboot=0')) { kp += ' inst.reboot=0' }
                    env.KERNEL_PARAMS = kp.trim()

                    echo "Kernel: ${env.KERNEL_URL}"
                    echo "Initrd: ${env.INITRD_URL}"
                    echo "Params: ${env.KERNEL_PARAMS}"
                }
            }
        }

        stage('Packer Build + Harden') {
            steps {
                withCredentials([
                    string(credentialsId: 'packer-ssh-password', variable: 'SSH_PASS'),
                    string(credentialsId: 'ansible-vault-pass', variable: 'VAULT_PASS')
                ]) {
                    sh '''
                        set -e
                        printf "%s" "$VAULT_PASS" > /tmp/vault_pass.txt
                        chmod 600 /tmp/vault_pass.txt

                        cd packer
                        packer init .

                        PKR_VAR_kernel_url="$KERNEL_URL" \
                        PKR_VAR_initrd_url="$INITRD_URL" \
                        PKR_VAR_kernel_params="$KERNEL_PARAMS" \
                        PKR_VAR_ssh_password="$SSH_PASS" \
                        PKR_VAR_image_name="${IMAGE_NAME}" \
                        PKR_VAR_ansible_dir="${WORKSPACE}/ansible" \
                        PKR_VAR_ansible_tags="${HARDENING_TAGS}" \
                        PKR_VAR_vault_pass_file="/tmp/vault_pass.txt" \
                        PACKER_LOG=1 packer build -force rhel.pkr.hcl
                    '''
                }
            }
        }

        stage('Upload Image') {
            steps {
                sh '''
                    scp -o StrictHostKeyChecking=no \
                        /var/lib/jenkins/packer-output/${IMAGE_NAME} \
                        frqadmin@192.168.122.1:/mnt/kvm_storage1/
                '''
            }
        }
    }

    post {
        always {
            sh 'rm -f /tmp/vault_pass.txt'
        }
    }
}